Error Page
Just-Rock-Stars/black-hole pull request #11
Opened 2023-05-31 12:33 UTC by ahikyoshi

1. Добавлена страница с ошибками
2. Заданы стили, контент, типизация

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-01 05:02 UTC, Qtrixnet approved these changes

2023-06-01 05:03 UTC, Qtrixnet requested changes

2023-06-01 05:03 UTC, Qtrixnet commented on packages/client/src/pages/Error/Error.tsx
> +          Sorry, we couldn’t find the page you’re looking for.
На русском же все таки решили делать)

2023-06-01 18:03 UTC, ahikyoshi commented on packages/client/src/pages/Error/Error.tsx
> +          Sorry, we couldn’t find the page you’re looking for.
Исправил

2023-06-03 13:38 UTC, Qtrixnet approved these changes

2023-06-03 13:39 UTC, merged