Feat/jus 12
Just-Rock-Stars/black-hole pull request #12
Opened 2023-06-03 10:10 UTC by Qtrixnet

### Какую задачу решаем
Создаем экран с описанием игры и добавляем хедер

### Скриншоты/видяшка (если есть)
![localhost_3000_](https://github.com/Just-Rock-Stars/black-hole/assets/67040346/e27276c5-549a-4b63-8a2f-67c0d06e3c98)
![localhost_3000_(iPhone XR)](https://github.com/Just-Rock-Stars/black-hole/assets/67040346/62cc1b5b-a7ea-4fcf-945a-1b259176defd)
### TBD (если есть)

2023-06-03 11:59 UTC, aleksandr-kiliushin requested changes

2023-06-03 11:59 UTC, aleksandr-kiliushin commented on packages/client/src/components/Modal/Modal.tsx
> +}
Несколько вещей можно улучшить:

1. Маунтить модалку можно напрямую в `document.body`, минуя parentElement – его наличие необязательно
<img width="1046" alt="image" src="https://github.com/Just-Rock-Stars/black-hole/assets/65129988/a04546ae-200c-4721-9ecb-96d4cbf0b4a5">

2. В эффекте сейчас делается то, что обычно делается просто через jsx. `appendChild()` == `return createElement()`. `removeChild()` == `return null`. То что в эффекте и то что в `return` в определенном смысле дублируют друг друга

3. В `return` можно избавиться от тернарника и уменьшить вложенность кода на один уровень за счет раннего `return`-а

Итоговый код вот

```suggestion
const Modal: FC<ModalProps> = ({ isOpen, title, children, onClose }) => {
  if (!isOpen) return null

  return createPortal(
    <div className="fixed flex flex-col inset-0 bg-white p-4">
      <div className="flex justify-end">
        {title && <header className="mr-auto">{title}</header>}
        <button onClick={onClose}>
          <IconClose width={ICON_SIZE} height={ICON_SIZE} />
        </button>
      </div>
      <div className="flex items-center justify-center grow">{children}</div>
    </div>,
    document.body
  )
}
```

2023-06-03 11:59 UTC, aleksandr-kiliushin commented on packages/client/src/components/Modal/types.ts
> +  onClose: VoidFunction
Класс, не знал про этот тип

2023-06-03 11:59 UTC, aleksandr-kiliushin commented on packages/client/src/components/Navbar/Navbar.tsx
> +        className={`${isVertical ? 'flex-col' : ''}
Эти ифы при составлении класснейма. Никита уже установил в своем PR либу clsx. Надо будет потом ее заюзать тут

2023-06-03 11:59 UTC, aleksandr-kiliushin commented on packages/client/src/components/icons/IconClose.tsx
> +// icon:close | CSS Icons https://css.gg/ | Astrit
Мб лучше либу с иконками установить, чтобы иконки не хранить в нашем сорс коде? В этом случае их не придется поддерживать, добавлять, удалять и тд

2023-06-03 11:59 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Home/Home.tsx
> +import { Hero } from '../../components/Hero'
Если компонент используется только на этой странице, не должен ли он лежать в `/pages/Home/Hero.js`?  

Иначе, если класть подобные компоненты в общие components, то:
- Какого размера будет папка components в реальном проекте?
- Как разруливать конфликты имен компонент в папке component? Получится что-то вроде `HomePageHero.js`, `AboutPageHero.js`, `MainPageHero.js`, хотя место кмк место им в папке с определенным роутом
- Зачем организовывать реэкспорт, если папка pages/Home не не имеет ничего кроме одного компонента (компонент Home.js)? Если одна из целей реэкспорта в index.js – определить то, что выдается из модуля наружу. , то это подразумевает, что в папке Home должны лежать еще компоненты кроме Home.js. Разве Hero.js не относится к этой категории компонентов?

2023-06-03 11:59 UTC, aleksandr-kiliushin commented on packages/client/src/components/Header/Header.tsx
> +      </Modal>
Согласно этой разметки, <Modal> является чилдерном `header`-а.  
Но на самом деле модалка не является чилдреном хедера ни семантически, ни визуально.  
Она скорее д.б. на одном уровне с хедером, внутри общего `React.Fragment`. Это также сделает разметку более плоской

2023-06-03 13:14 UTC, Qtrixnet commented on packages/client/src/components/Navbar/Navbar.tsx
> +        className={`${isVertical ? 'flex-col' : ''}
Да да, специально пока так сделал,  чтоб не ставить в своей ветке)

2023-06-03 13:18 UTC, Qtrixnet commented on packages/client/src/components/icons/IconClose.tsx
> +// icon:close | CSS Icons https://css.gg/ | Astrit
Не вопрос, можем вынести это в чатик и выбрать

2023-06-03 13:28 UTC, Qtrixnet commented on packages/client/src/pages/Home/Home.tsx
> +import { Hero } from '../../components/Hero'
Я конечно не вижу причин именно для этого компонента, но если мы захотим использовать hero на других страницах, то его придется переносить в папку components. Возможно тогда нам лучше делить проект еще на части? сущности какие-то или модули, где внутри каждой будет своя папка components?

- В реальном проекте и архитектура немного другая, как раз поделенная на модули, где структура исключает такое раздувание папки)
- В данном примере не должно быть конфликтов конечно, потому что семантически hero должен быть один
- Реэкспорты это же как раз та неразрешенная тема, по которой мы собрались пройти после слияния всех веток, поэтому пока они сделаны в консистентном с остальными компонентами стиле. Было бы странно если бы одни компоненты экспортировались из файла напрямую, а другие через индекс?

2023-06-03 13:29 UTC, Qtrixnet commented on packages/client/src/components/Header/Header.tsx
> +      </Modal>
Действительно, так будет намного лучше 👍🏼

2023-06-04 06:00 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Home/Home.tsx
> +import { Hero } from '../../components/Hero'
> _Возможно тогда нам лучше делить проект еще на части? сущности какие-то или модули, где внутри каждой будет своя папка components?_  

`pages/Home/` разве не та самая папка где лежат компоненты относящиеся к Home?  

> _В данном примере не должно быть конфликтов конечно, потому что семантически hero должен быть один_  

Судя по его наполнению, он не выглядит переиспользуемым. Если вдруг он все же потребуется на другой странице, тогда и вынесем его к общим компонентам.  
Предлагаю рассматривать компоненты как local-by-default вместо shared-by-default и по необходимости выносить из local (src/pages/Home/Hero.js) в shared (src/components/Hero.js).

На счет реэкспорта, я неясно выразился. Это ок, что он тут есть, он и потом останется. Имею ввиду, что в принципе использование реэкспортов использование предполагает определенное наполнение папки `pages/Home/`: что там должно быть не только `index.js` и `Home.js`. Например, в ней может быть 10 файлов с дочерними компонентами, утилитами, а экспортируется только 2 компонента и 1 утилита из них. То есть в ней должно быть что-то еще, иначе зачем вообще папка? И это что-то – ничто иное, как дочерние компоненты компоненты `<Home />`

2023-06-04 06:20 UTC, Qtrixnet commented on packages/client/src/pages/Home/Home.tsx
> +import { Hero } from '../../components/Hero'
Согласен с local-by-default, сделаем

_"Например, в ней может быть 10 файлов с дочерними компонентами, утилитами, а экспортируется только 2 компонента и 1 утилита из них"_ - так вот если экспорируются оттуда несколько компонентов и утилит, это же как раз ситуация когда local компоненты становятся shared и их надо выносить?

`что там должно быть не только index.js и Home.js`  - папки даже с одним файлом компонента мы создаем консистентности структуры и на случай, если понадобится вынести туда типы, добавить локальные утилиты и тп. Чтобы в конечном итоге у нас не лежали одни компоненты в папках с реэкспортом, а другие просто файликами. Будет же беспорядок

2023-06-04 06:33 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Home/Home.tsx
> +import { Hero } from '../../components/Hero'
> так вот если экспорируются оттуда несколько компонентов и утилит, это же как раз ситуация когда local компоненты становятся shared и их надо выносить?  

Резонно. На pages это действительно не распространяется, из него всегда будет экспортироваться только один компонент страницы

И на счет консистентности согласен

2023-06-04 06:53 UTC, Qtrixnet commented on packages/client/src/components/Modal/Modal.tsx
> +}
Спасибо за развернутый ответ, на самом деле такой вариант и мне нравится больше
Сначала я хотел немного оспорить) потому что изначальная идея была в том, что я передаю isOpen пропс для того, чтобы модалка могла сохранять свои состояния и анимации, и думал что вся задумка накроется если я буду монтировать без эффекта, но тесты показали, что все прекрасно работает)

2023-06-04 08:16 UTC, aleksandr-kiliushin approved these changes

2023-06-07 06:42 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Home/parts/Hero/Hero.tsx
> +import { GAME_NAME } from '../../../../utils/global'
@Qtrixnet на всякий случай, уже сделал в [этом](https://github.com/Just-Rock-Stars/black-hole/pull/16) PR, так что можно не делать

2023-06-07 18:40 UTC, merged