Feat/jus 16
Just-Rock-Stars/black-hole pull request #13
Opened 2023-06-03 16:10 UTC by ahikyoshi

### Какую задачу решаем

Верстка форума

### Скриншоты/видяшка (если есть)

![2023-06-03_19-09-51](https://github.com/Just-Rock-Stars/black-hole/assets/115409269/9afbd9a6-4143-409c-bfe9-b2cc716ae765)
![2023-06-03_19-09-38](https://github.com/Just-Rock-Stars/black-hole/assets/115409269/e5243bc7-c089-43c8-9068-0de1763f8db0)
![2023-06-03_19-09-04](https://github.com/Just-Rock-Stars/black-hole/assets/115409269/6835d259-3767-403c-9def-c6a8d0971e91)

### TBD (если есть)

2023-06-03 16:42 UTC, aleksandr-kiliushin requested changes

2023-06-03 16:42 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +  const testList = [
Т.к. это не зависит от пропов, можно вынести это из компонента. Понимаю, что он тут временно и тд, но можно вынести все равно, и типизировать

2023-06-03 16:42 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +          {testList.map((item, index) => {
Вместо `item` и `index` можно дать более говорящие названия, например `topic` и `topicIndex`. Так легче читать код ниже

2023-06-03 16:42 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Components/Topic.tsx
> +      {testTopic.map(item => {
тож, имя `message` даст больше контекста и инфы ниже по кода, чем `item`

2023-06-03 16:42 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Forum.tsx
> +// Core
Эти комменты можешь не писать, сделаем автосортировку импортов по категориям

2023-06-03 16:42 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Forum.tsx
> +import { ForumList } from './Components/ForumList'
папку `Components` наверное надо с маленькой буквы назвать: `components` (по аналогии с utils, constants, types, pages)  
Это даст понять, что там много всякого разного лежит, а не какой-то один класс или компонент с именем `Components`

2023-06-03 16:42 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Forum.tsx
> +import { ForumList } from './Components/ForumList'
Если будешь переименовывать, то возможно столкнешься с проблемой

Гит может проигнорировать изменение регистра в имени папки и не воспринять его как дифф. В итоге, в удаленном репозитории папка останется `Components`, а локально у тебя будет `components`  

Чтобы решить эту проблему, погугли про настройку gitconfig core.ignorecase

Если не разберешься или это не поможет, сделай 2 коммита:
1. переименовывает Components на componentsLALA
2. переименовывает componentsLALA на components

2023-06-03 17:45 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +    setTheme({ data: testList })
Тут понятно, что темы попадут в состояние только после запроса на сервер, но в данном кейсе лучше вообще убрать эффект и в инишиал стейт положить сразу testList. Иначе в таком случае сначала будет рендер с пустым массивом, а после него запустится эффект, который изменит стейт и запустит второй рендер

2023-06-03 17:46 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +        Сообщество Blackhole
для названия игры есть константа GAME_NAME

2023-06-03 17:48 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +          {theme.data.map((theme, themeIndex) => {
если мы будем добавлять функциональность добавления/редактирования/удаления тем, то нужно либо id прокидывать в key, либо устанавливать и юзать uuid / nanoid, чтоб после изменения одной темы не было сюрпризов в разметке

2023-06-03 17:49 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +                  <div className="text-indigo-600 text-2xl">{theme.title}</div>
ключи можно сразу достать:

({title, discribe, countOfThemes, countOfAnswers}, themeIndex)

2023-06-03 17:50 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/Topic.tsx
> +    setMessages({ data: testTopic })
same as forumlist

2023-06-03 17:50 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/TopicList.tsx
> +    setTopic({ data: testTopicList })
same as forumlist

2023-06-03 17:51 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +                  <div className="text-indigo-600 text-2xl">{theme.title}</div>
Ты противоречишь Саше который выше мне сказал сделать иначе
Мне как делать?

2023-06-03 17:51 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Components/Topic.tsx
> +    setMessages({ data: testTopic })
А разве есть другой способ отрендерить данные которые пришли с сервера, кроме как через useEffect?

2023-06-03 17:52 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +                  <div className="text-indigo-600 text-2xl">{theme.title}</div>
Я допустим больше склоняюсь не к деструктуризации, а к обозначению которое я сделал

2023-06-03 17:55 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +                  <div className="text-indigo-600 text-2xl">{theme.title}</div>
в чем преимущество каждый раз прописывать theme.title, если ты можешь сразу достать все ключи на входе?

2023-06-03 17:56 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/Topic.tsx
> +    setMessages({ data: testTopic })
нет, я имею в виду, что в текущем контексте нет никаких запросов на сервер и вместо того, чтобы сначала вызывать рендер с пустым массивом, а потом менять его в эффекте, ты можешь сразу создать стейт с нужными данными:

 const [messages, setMessages] = useState<MessagesTypes>({ data: testTopic })
 
 тогда нее будет лишнего рендера

2023-06-03 17:57 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Components/Topic.tsx
> +    setMessages({ data: testTopic })
Ааа, понял

2023-06-03 17:58 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +                  <div className="text-indigo-600 text-2xl">{theme.title}</div>
Ладно убедил

2023-06-03 17:58 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +          {theme.data.map((theme, themeIndex) => {
Сейчас же его нет, мне что туда пробрасывать?

2023-06-03 18:00 UTC, Qtrixnet commented on packages/client/src/pages/Forum/Components/ForumList.tsx
> +          {theme.data.map((theme, themeIndex) => {
так как сейчас мы не можем редактировать, то проблем не возникнет. Но ты можешь заранее создать id у себя в моках, либо использовать для ключей  uuid / nanoid, чтоб потом не забыть и случайно не оставить индекс, когда будет добавляться функциональность редактирования

2023-06-03 18:20 UTC, Qtrixnet commented on packages/client/src/pages/Forum/components/TopicList.tsx
> +              <div className="">{lastPublic.time}</div>
просто для инфы еще добавлю, что можно было пойти дальше)

{ title, answers, author, lastPublic:  {time, author}, id }

2023-06-04 03:52 UTC, aleksandr-kiliushin approved these changes

2023-06-08 14:45 UTC, closed without merging