style: Configure import aliases, import order and code formatting
Just-Rock-Stars/black-hole pull request #16
Opened 2023-06-06 18:06 UTC by aleksandr-kiliushin

2023-06-13 04:57 UTC, romka008 requested changes

2023-06-13 04:57 UTC, romka008 commented on packages/client/src/pages/SignIn/SignIn.tsx
>      } catch (error) {
В Данной реализации этот блок кода никогда не выполнится.
У нас при нажатии на кнопку "Войти", если что-то было не так, то над кнопкой появлялся текст, сейчас это не работает.

Сейчас происходит обновление страницы при нажатии на кнопку "Войти", ранее этого не было. 

![Снимок7](https://github.com/Just-Rock-Stars/black-hole/assets/78255568/551f927e-cdf3-451d-bf02-276394194837)

2023-06-13 04:57 UTC, romka008 commented on packages/client/src/pages/SignUp/SignUp.tsx
>      } catch (error) {
Та же проблема, что и на странице входа, данный блок кода никогда не выполнится.

2023-06-13 04:57 UTC, romka008 commented on packages/client/src/pages/Profile/FormChangeUserData/FormChangeUserData.tsx
>  import { FC } from 'react';
В Профиле, при нажатии на кнопку "Сохранить" происходит обновление страницы, ранее не было.

2023-06-13 04:57 UTC, romka008 commented on packages/client/src/pages/Profile/FormChangeUserData/FormChangeUserData.tsx
> +        validationError={errors.email?.message}
Здесь ошибочка, должно быть:
validationError={errors.phone?.message}

2023-06-13 05:10 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Profile/FormChangeUserData/FormChangeUserData.tsx
> +        validationError={errors.email?.message}
Исправил

2023-06-13 05:32 UTC, Qtrixnet commented on packages/client/src/components/ErrorBoundary/ErrorBoundary.tsx
> +            <button className="btn btn-primary ml-3" onClick={window.location.reload}>
Здесь точно релоад корректно работает? в таком виде он же сразу вызывается не дожидаясь клика

2023-06-13 05:32 UTC, Qtrixnet commented on .prettierrc
> +  "importOrder": [
о, алиасы, огонь!

2023-06-13 05:32 UTC, Qtrixnet commented on packages/client/src/components/Header/Header.tsx
> +        <Navbar orientation="vertical" />
почему так? здесь же всего 2 состояния, булевый флаг кажется отлично подходил. Плюс теперь это обязательный пропс

2023-06-13 05:32 UTC, Qtrixnet commented on packages/client/src/utils/randomAvatarPath.ts
> +export const randomAvatarPath = `https://api.dicebear.com/6.x/adventurer-neutral/svg?seed=${Math.random()}&radius=20`;
путь перестал быть константным из-за math.random?

2023-06-13 05:33 UTC, Qtrixnet commented
Рефакторинг конечно мое почтение, солидный вклад в проект)

2023-06-13 06:13 UTC, aleksandr-kiliushin commented on packages/client/src/components/ErrorBoundary/ErrorBoundary.tsx
> +            <button className="btn btn-primary ml-3" onClick={window.location.reload}>
дожидается  
Вот так бы не дожидался: `onClick={window.location.reload()}`

2023-06-13 06:14 UTC, aleksandr-kiliushin commented on packages/client/src/utils/randomAvatarPath.ts
> +export const randomAvatarPath = `https://api.dicebear.com/6.x/adventurer-neutral/svg?seed=${Math.random()}&radius=20`;
Да

2023-06-13 07:57 UTC, Qtrixnet commented on packages/client/src/components/ErrorBoundary/ErrorBoundary.tsx
> +            <button className="btn btn-primary ml-3" onClick={window.location.reload}>
а, ой

2023-06-13 14:08 UTC, aleksandr-kiliushin commented on packages/client/src/pages/SignUp/SignUp.tsx
>      } catch (error) {
Откатил как было, ошибки отображаются

2023-06-13 14:09 UTC, aleksandr-kiliushin commented on packages/client/src/pages/SignIn/SignIn.tsx
>      } catch (error) {
Откатил как было, ошибки отображаются

2023-06-13 14:09 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Profile/FormChangeUserData/FormChangeUserData.tsx
>  import { FC } from 'react';
Откатил как было, больше не обновляется

2023-06-13 14:45 UTC, aleksandr-kiliushin commented on packages/client/src/components/Header/Header.tsx
> +        <Navbar orientation="vertical" />
`orientation: "horizontal" | "vertical"` – более явный и самодокументируемый вариант пропов, по сравнению с опциональными булевыми флагами. Снаружи компонента сразу видно, что vertical – это именно ориентация (хотя да, что же еще если не ориентация), а также TS подсказывает, какие вообще варианты есть (`"horizontal" | "vertical"`).  

Ниже несколько примеров (местами, абсурдных), чтобы передать что имею ввиду

```
// Пример 1
type NavbarProps = { isVertical?: boolean }
<Navbar isVertical />

type NavbarProps = { orientation: "horizontal" | "vertical" }
<Navbar orientation="vertical" />


// Пример 2
type ButtonProps = { isPrimary?: boolean, isSecondary?: boolean }
<Button isPrimary />

type ButtonProps = { variant: "primary" | "secondary" }
<Button variant="primary" />

// Пример 3
type NewsListProps = { isLoading?: boolean, isSuccess?: boolean, isError?: boolean }
<NewsList isError isSuccess />

type NewsListProps = { status: "loading" | "success" | "error" }
<NewsList status="loading" />
```

На счет дефолтных значений пропов: чтобы значение пропа стало могло претендовать на дефолтное, оно должно выделяться из множества значений своей очевидностью и высокой вероятностью. Например, isDisabled у кнопки – хороший пример. Если мы не указываем задизейбленность у кнопки, она по умолчанию будет задизейблена или нет? Очевидно, что нет.  
```
type ButtonProps = { isDisabled?: boolean }
const Button = ({ isDisabled = false }: ButtonProps) => { ... }
<Button />
<Button isDisabled />
```
А про ориентацию навбара сложно выбрать дефолтное значение, потому что вертикальное и горизонтальное расположение равноценны

2023-06-13 17:19 UTC, romka008 approved these changes

2023-06-14 05:48 UTC, merged

2023-06-14 15:38 UTC, Qtrixnet commented on packages/client/src/components/Header/Header.tsx
> +        <Navbar orientation="vertical" />
Ой, ну сложно, опять холиварная тема) конкретно с этим компонентом я не согласен) но уже оставим как есть