Forum
Just-Rock-Stars/black-hole pull request #17
Opened 2023-06-08 15:13 UTC by ahikyoshi

Add Forum Page, topics list and topic

### Какую задачу решаем

Создание форума

1. Создание списка разделов форума
2. Список топов, и возможность создания новых
3. Обсуждение проблемы, возможность ответить или написать новое сообщение в обсуждение

2023-06-08 17:13 UTC, aleksandr-kiliushin requested changes

2023-06-08 17:13 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/types.ts
> +}
Лишняя вложенность во всех типах в этом файле: `data { ... }`.  
Ее можно убрать. Например, вместо `MessagesTypes` экспортни отсюда тип  Message. Будет `useState<Message[]>`. Иметь отдельный тип для сообщения в единственном числе (а не для массива сообщений)удобнее для разных манипуляций. Он пригодится например в будущем компоненте `<Message />`

То же самое с остальными типами в этом файле

```suggestion
export interface Message {
  author: string;
  message: string;
  time: string;
  id: string;
}
```

2023-06-08 17:13 UTC, aleksandr-kiliushin commented on packages/client/src/providers/Router/AppRouter/constants.ts
> +  [AppRoutes.TOPIC]: '/forum/:idTopicList/topics/:idTopic',
1. idTopicList -> topicListId?  
2. idTopic -> topicId?  
3. В итоге называем это topic или theme? Или это разные сущности?

2023-06-08 17:13 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/types.ts
> +    countOfThemes: number;
Что значит countOfThemes внутри theme? Как их может быть несколько?

2023-06-08 17:13 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/types.ts
> +    discribe: string;
describe – что сделать / описать / действие / функция  
description – что такое / описание / существительное / строка

2023-06-08 17:13 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/types.ts
> +    message: string;
Чтобы в коде не было message.message, можно дать этому полю другое название: body, text или content. Ведь это действительно лишь текст сообщения, а не само сообщение

2023-06-08 17:13 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/TopicList.tsx
> +  const [isNewTopicOpen, setIsNewTopicOpen] = useState(false);
Отл нейминг для булевых

2023-06-08 17:13 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/ForumList.tsx
> +        <div className="text-4xl py-3 text-slate-700">
<h1> мб? это заголовок страницы?

2023-06-09 08:01 UTC, ahikyoshi commented on packages/client/src/providers/Router/AppRouter/constants.ts
> +  [AppRoutes.TOPIC]: '/forum/:idTopicList/topics/:idTopic',
А это делал Рома а не я

2023-06-09 14:13 UTC, romka008 requested changes

2023-06-09 14:13 UTC, romka008 commented on packages/client/src/pages/Forum/TopicList.tsx
> +                <AppLink to={`/forum/:idTopicList/topics/${id}`}>
В данном случае это не будет работать так, как задумывалось. 
Сейчас при переходе к определенной теме у тебя сл. урл: "/forum/:idTopicList/topics/8bxnesczx4", а вместо idTopicList должен быть id из твоего массива testList компоненты ForumList.

Тебе необходимо передать переменную idTopicList, которую ты можешь взять из урла при помощи хука useParam библиотеки 'react-router-dom':
const { idTopicList } = useParams();
<AppLink to={`/forum/${idTopicList}/topics/${id}`}>

2023-06-09 14:55 UTC, aleksandr-kiliushin approved these changes

2023-06-10 07:44 UTC, romka008 approved these changes

2023-06-13 10:30 UTC, merged