JUS-36 Добавлен Fullscreen API
Just-Rock-Stars/black-hole pull request #20
Opened 2023-06-17 10:30 UTC by romka008

### Какую задачу решаем
## Добавить минимум одну Web API
Добавлен Fullscreeen API (компонент MaximizableView) и хук useFullscreenStatus.
В MaximizableView необходимо передать цвет для фона в props "backgroundColor".
MaximizableView можно использовать чтобы дать возможность развернуть на полный экран любой компонент, пример использования:
`<MaximizableView backgroundColor="#ffffff"> <SomeComponent/> </MaximizableView>`

В компонент Topic добавлена возможность развернуть на весь экран блок с комментариями.

### Скриншоты/видяшка (если есть)
![Снимок10](https://github.com/Just-Rock-Stars/black-hole/assets/78255568/edc1dfec-2f68-49a9-a03b-cfa909d3aad7)
![Снимок11](https://github.com/Just-Rock-Stars/black-hole/assets/78255568/b701455f-c4bb-4ef4-9bf2-f6ba98bfb251)

### TBD (если есть)

2023-06-17 12:33 UTC, aleksandr-kiliushin requested changes

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +      onClick={handleExitFullscreen}
Создание `handleExitFullscreen` нужно
```suggestion
      onClick={document.exitFullscreen}
```

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +        isFullscreen ? 'flex-col-reverse content-end items-center pt-4 pl-4' : ''
Конкатенация классов легче читается если использовать clsx

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +  try {
Этот try catch в теле компонента подсказывает, что хук `useFullscreenStatus` должен возвращать в том числе поле `isFullscreenApiSupported`, чтобы не вычислять его тут

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +    const fullscreen = useFullscreenStatus(maximizableElement);
```suggestion
    const { isFullscreen, setIsFullscreen } = useFullscreenStatus(maximizableElement);
```

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/utils/useFullscreenStatus.ts
> +  React.useLayoutEffect(() => {
`useState` импортируется отдельно, а `useLayoutEffect` и `RefObject` берутся из `React.`. Одно и то же сделано разными способами, мб лучше все импортировать в одном стиле?

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Topic.tsx
> +        <MaximizableView backgroundColor="#ffffff">
Использовать фулскрин для чего-то кроме канваса с игрой, кажется, нет смысла

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/utils/useFullscreenStatus.ts
> +    fsDoc[getBrowserFullscreenElementProp()] !== null
Начальное состояние isFullscreen мб должно быть просто `false`?

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/utils/useFullscreenStatus.ts
> +export const useFullscreenStatus = (elRef: React.RefObject<HTMLElement>) => {
(осторожно, мнение)  
Такие сокращения, как `elRef` и `fsDoc` профита не дают, а лишь вводят в заблуждения при чтении кода.  

Исправлять необязательно, просто делюсь наблюдениями

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/utils/useFullscreenStatus.ts
> +    throw new Error('fullscreenElement не поддерживается вашим браузером');
Если фулскрин не поддерживается, то приложение сломается? Будет экран "Что-то пошло не так"?

2023-06-17 12:33 UTC, aleksandr-kiliushin commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +  const fullscreenButton = isFullscreen ? (
(мнение)  
Создание jsx-а `fullscreenButton` в теле функционального компонента == создание метода `rednerFullscreenButton` в классовом компоненте == усложнение поддержки компонента

Это лучше вынести в отдельный компонент `FullscreenButton` или просто заинлайнить, тк тут всего 10 строк

Исправлять необязательно, просто делюсь наблюдениями

2023-06-17 14:06 UTC, romka008 commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +      onClick={handleExitFullscreen}
Так будет ошибка: 
`Uncaught (in promise) TypeError: Failed to execute 'exitFullscreen' on 'Document': Illegal invocation
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at react-dom.development.js:9288:12
    at batchedUpdates$1 (react-dom.development.js:26140:12)
c`
Можно написать так `onClick={() =>document.exitFullscreen()}`

2023-06-17 14:19 UTC, romka008 commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +        isFullscreen ? 'flex-col-reverse content-end items-center pt-4 pl-4' : ''
Хорошо, используем

2023-06-17 14:20 UTC, romka008 commented on packages/client/src/utils/useFullscreenStatus.ts
> +  React.useLayoutEffect(() => {
Поправил

2023-06-17 14:38 UTC, romka008 commented on packages/client/src/pages/Forum/Topic.tsx
> +        <MaximizableView backgroundColor="#ffffff">
Думаю, что Fullscreen API используется не только в canvas (играх), я попробую данную реализацию как-то адаптировать для canvas

2023-06-17 14:48 UTC, Qtrixnet approved these changes

2023-06-17 15:01 UTC, romka008 commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +  try {
В данном коде в блоке try catch я проверяю, не вернулась ли мне ошибка при передачи определенного рефа в useFullscreenStatus, и если вернулась ошибка (она возвращается из функции getBrowserFullscreenElementProp), что означает => фуллскрин для браузера не поддерживается, я выполняю блок кода из catch

2023-06-17 15:06 UTC, romka008 commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +    const fullscreen = useFullscreenStatus(maximizableElement);
В блоке try/catch я присваиваю уже объявленным переменным isFullscreen, setIsFullscreen значения, поэтому пришлось сделать именно так: 
`const fullscreen = useFullscreenStatus(maximizableElement);`

2023-06-17 15:08 UTC, romka008 commented on packages/client/src/utils/useFullscreenStatus.ts
> +    fsDoc[getBrowserFullscreenElementProp()] !== null
Согласен, можно так сделать, поправил

2023-06-17 15:14 UTC, romka008 commented on packages/client/src/utils/useFullscreenStatus.ts
> +    throw new Error('fullscreenElement не поддерживается вашим браузером');
Если фуллскрин не поддерживается приложение не упадет, не будет никакого экрана, 
В блоке catch компонента MaximizableView переменной errorMessage добавлялся текст "Полноэкранный режим не поддерживается" (сейчас текст кнопки меняться не будет) и при нажатии на неё появляется алерт
![Снимок12](https://github.com/Just-Rock-Stars/black-hole/assets/78255568/a0252c29-7dfe-4dc2-a53b-6e8db24cb484)

2023-06-17 15:16 UTC, romka008 commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +  const fullscreenButton = isFullscreen ? (
Заинлайнил

2023-06-17 15:18 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Topic.tsx
> +        <MaximizableView backgroundColor="#ffffff">
Ни разу не видел, но мб и используется где-то в онлайн-кинотеатрах или онлайн-квестах. Но наверняка не для таких вещей как список пользователей. Хедер сайта будет скрыт и недоступен. Также предполагаю, что не будут отображаться такие вещи как всплывающие уведомления, тк они монтируются в куда-то в `body` и не являются чилдренами `MaximizableView`

2023-06-17 15:28 UTC, aleksandr-kiliushin commented on packages/client/src/utils/useFullscreenStatus.ts
> +    throw new Error('fullscreenElement не поддерживается вашим браузером');
Точно, там же try-catch

2023-06-17 17:41 UTC, Olegas requested changes
1. Замечание к реализации хука - блокирующее
2. Соглашусь с @aleksandr-kiliushin - использовать фулскрин для форума несколько странно. Но этот комментарий не блокирует приемку задачи.

2023-06-17 17:41 UTC, Olegas commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +  try {
Согласен с @aleksandr-kiliushin - API получилось странное. Требуется try/catch и т.п.
Лучше это инкапсулировать внутри, не выкидывать из хука ошибку наружу а возвращать все что нужно для работы из хука, что бы его потребители не думали о деталях его реализации. Достаточно флага который покажет что все ок или не ок. Там же вернуть пустую функцию вместо setIsFullscreen и false в isFullscreen

2023-06-18 15:48 UTC, romka008 commented on packages/client/src/components/MaximizableView/MaximizableView.tsx
> +  try {
Спасибо за ревью, поправил, и немного изменил. Теперь если в браузере не поддерживается fullscreen API, то и кнопки не будет.

2023-06-18 17:37 UTC, Olegas requested changes
Стало лучше. Есть два небольших замечания к коду хука. Давай их исправим и будет апрув.

2023-06-18 17:37 UTC, Olegas commented on packages/client/src/utils/useFullscreenStatus.ts
> +  React.useEffect(() => {
Вот эти вычисления лучше перенести в useState выше.
Как-то так:
useState(() => { ... doc[getBrowserFullscreenElementProp()]; ... })

Иначе первый рендер будет с isFullscreenApiSupported = true а затем произойдет перерендер уже с false (если вдруг API не поддерживается). Это может быть заметно глазом - моргнет какой-то интерфейсный элемент например.

2023-06-18 17:37 UTC, Olegas commented on packages/client/src/utils/useFullscreenStatus.ts
> +  const setFullscreen = () => {
Эту функцию лучше завернуть в useCallback, иначе будем на каждую отрисовку делать ее новую и возвращать компоненту, который использует этот хук

2023-06-18 18:45 UTC, aleksandr-kiliushin approved these changes

2023-06-19 04:14 UTC, kluk42 approved these changes

2023-06-19 07:12 UTC, Olegas approved these changes
👍

2023-06-19 12:46 UTC, merged