Feat/jus 31
Just-Rock-Stars/black-hole pull request #22
Opened 2023-06-18 10:37 UTC by kluk42

### Какую задачу решаем
Игровая механика

2023-06-18 19:09 UTC, aleksandr-kiliushin approved these changes

2023-06-18 19:09 UTC, aleksandr-kiliushin commented on packages/client/src/store/slices/gameStats/gameStatsSlice.ts
> +      (state.maxSize = maxSize), (state.playTime = playTime), (state.points = points);
```suggestion
      state.maxSize = maxSize
      state.playTime = playTime
      state.points = points
```

2023-06-18 19:09 UTC, aleksandr-kiliushin commented on packages/client/src/store/slices/gameStats/types.ts
> +  playTime: number | null;
Если под этим понимается не момент времени, продолжительность, то лучше назвать не `playTime`, а `playDuration`

2023-06-18 19:09 UTC, aleksandr-kiliushin commented on packages/client/src/store/slices/gameStats/types.ts
> +  maxSize: number | null;
Нужно ли отдельное состояние maxSize? Может быть сделаем его функцией от кол-ва очков? Сейчас состояния points и maxSize дублируют друг друга в какой-то мере.  
И на счет нейминга, наверное должен быть holeSize, а не maxSize. Так как очки названы просто points, а не maxPoints

2023-06-19 03:37 UTC, kluk42 commented on packages/client/src/store/slices/gameStats/gameStatsSlice.ts
> +      (state.maxSize = maxSize), (state.playTime = playTime), (state.points = points);
это претир так сделал при форматировании на сохранение. Я даже не знал про такой синтаксис раньше :)

2023-06-19 03:42 UTC, kluk42 commented on packages/client/src/store/slices/gameStats/types.ts
> +  maxSize: number | null;
Очки могут уменьшаться и увеличиваться во время игры, поэтому кмк невозможно из конечного количества очков вычислить максимальное количество очков за игру. Наверное название конфьюзит, правильнее maxSize переименовать в maxPoints

2023-06-19 19:47 UTC, Olegas requested changes
По самой игровой механике вопросов нет, код написан понятно, удобно разбит на небольшие файлы, читать удобно 👍
Кажется есть проблема с тем, что анимация никогда не останавливается + есть мелкие замечания по выводу продолжительности игры - написал комментарии в коде

2023-06-19 19:47 UTC, Olegas commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +            <span className="font-bold text-rose-500"> {playTimeInSeconds} </span>
Тут может получиться не целое число. Не надо ли дробную часть убрать? И нужны ли пробелы вокруг значений? Если это сделать для того, что бы добавить промежуток между комментарием и значением, то это надо делать через CSS

2023-06-19 19:47 UTC, Olegas commented on packages/client/src/pages/Game/holeHandlers.ts
> +  const isHoleGoingBeyondCeil = gameState.hole.y + step < HOLE_RADIUS && step < 0;
gameState.hole вынесено в переменную на 21 строке

2023-06-19 19:47 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
>    }, []);
А как остановить анимацию когда игра закончится? Там ведь (внутри requestAnimation) по сути бесконечный цикл

2023-06-20 11:15 UTC, kluk42 commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +            <span className="font-bold text-rose-500"> {playTimeInSeconds} </span>
А если через &nbsp;?

2023-06-20 19:48 UTC, Olegas commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +            <span className="font-bold text-rose-500"> {playTimeInSeconds} </span>
Так, стоп, я понял. Если речь идет о том что бы просто пробел добавить между строками то конечно nbsp подойдет. Так же как и {' '} например.
Меня смутил тот факт что у вас пробелы были с двух сторон вокруг значения, потому я и подумал что это какое-то украшательство, для которого выбран неправильный способ.
Тут вопрос закрыт, все хорошо

2023-06-20 19:49 UTC, Olegas approved these changes
Принято. Молодец!

2023-06-21 03:48 UTC, merged