JUS-52 Добавлено mеdia API (музыка)
Just-Rock-Stars/black-hole pull request #29
Opened 2023-07-07 14:11 UTC by romka008

### [Добавлено mеdia API (музыка)]
В компонент с игрой Добавлен компонент Audio, есть возможность отключить/включить музыку и прибавить или убавить звук.

### Скриншоты/видяшка (если есть)
![Музыка](https://github.com/Just-Rock-Stars/black-hole/assets/78255568/dbe0916b-50d1-46fb-ac81-3ccd17706b2a)

2023-07-07 14:30 UTC, Qtrixnet requested changes

2023-07-07 14:30 UTC, Qtrixnet commented on packages/client/src/components/Audio/Audio.tsx
> +            <img
Думаю, что элементы управления все таки должны быть кнопками

2023-07-07 14:30 UTC, Qtrixnet commented on packages/client/src/components/Audio/Audio.tsx
> +  const handleVolumeMinus = () => {
может вместо 2х функций сделать что нибудь подобное?

```
const handleVolumeChange = (change: 'increase' | 'decrease') => {
    if (!audioRef.current) {
      return;
    }

    if (change === 'increase' && roundToOne(audioRef.current.volume) !== 1.0) {
      audioRef.current.volume += 0.1;
    } else if (change === 'decrease' && roundToOne(audioRef.current.volume) !== 0.0) {
      audioRef.current.volume -= 0.1;
    }
  };
```

2023-07-07 14:30 UTC, Qtrixnet commented on packages/client/src/store/slices/sound/soundSlice.ts
> +  isPlay: false,
может музыку включим по умолчанию?) сразу погрузим пользователя в атмосферу

2023-07-07 14:47 UTC, aleksandr-kiliushin commented on packages/client/src/components/Audio/Audio.tsx
> +  const handleVolumeMinus = () => {
Отдельные функции без параметров, как сейчас – это ок, думаю  
А на счет конструкции с `return` согласен

```
const fn = () => {
  if (!audioRef.current) { return; }
  if (roundToOne(audioRef.current.volume) === 1.0) { return }
  audioRef.current.volume += 0.1;
}
```

2023-07-07 14:48 UTC, aleksandr-kiliushin approved these changes

2023-07-07 18:43 UTC, romka008 commented on packages/client/src/store/slices/sound/soundSlice.ts
> +  isPlay: false,
Включаю!)

2023-07-07 18:43 UTC, romka008 commented on packages/client/src/components/Audio/Audio.tsx
> +  const handleVolumeMinus = () => {
Сделал даже чуть по другому)
`const handleVolumePlus = () => {
    if (!audioRef.current || roundToOne(audioRef.current.volume) === 1.0) {
      return;
    }
    audioRef.current.volume += 0.1;
  };`

2023-07-07 18:43 UTC, romka008 commented on packages/client/src/components/Audio/Audio.tsx
> +            <img
Есть!

2023-07-07 18:43 UTC, romka008 commented on packages/client/src/assets/images/icons/volume-minus.svg
Готово

2023-07-07 19:03 UTC, Qtrixnet approved these changes

2023-07-08 05:03 UTC, kluk42 commented on packages/client/src/components/Audio/Audio.tsx
> +  const isPlay = useAppSelector((state) => state.sound.isPlay);
А почему решил в редаксе состояние хранить?

2023-07-08 09:30 UTC, IvanPeleshok commented on packages/client/src/components/Audio/Audio.tsx
> +    if (ref) {
Проверку на ref предлагаю убрать, обращаясь следующим образом:
```
ref?.addEventListener('ended', handleTrackEnded);
```

2023-07-08 09:30 UTC, IvanPeleshok commented on packages/client/src/components/Audio/Audio.tsx
> +      if (ref) {
Аналогично

2023-07-08 09:32 UTC, IvanPeleshok commented on packages/client/src/components/Audio/Audio.tsx
> +    audioRef.current.volume -= 0.1;
Пожелание: после условий делать пустой абзац, так код будет немного читаемее из-за того, что логические блоки будет иметь разрывность

2023-07-08 09:34 UTC, IvanPeleshok commented on packages/client/src/components/Audio/Audio.tsx
> +            {isPlay ? (
Предлагаю стилестически другой подход для тернарников:
```
условие
  ? <Component1 />
  : <Component2 />

```

2023-07-08 09:35 UTC, IvanPeleshok requested changes
Есть небольшие замечания

2023-07-08 19:00 UTC, romka008 commented on packages/client/src/components/Audio/Audio.tsx
> +  const isPlay = useAppSelector((state) => state.sound.isPlay);
@kluk42 Все верно, состояние специально добавлено в редакс, чтобы при переходи между страницами, состояние музыки включено/выключено сохранялось, а также состояние сохраняется если я попал на страницу "/game-end", а далее нажимаю на кнопку поглотить вселенную снова. 
Используя локальный стэйт, при переходе на роут с самой игрой, состояние будет всегда то, которое существует при первом моунте страницы с игрой.

2023-07-08 19:29 UTC, romka008 commented on packages/client/src/components/Audio/Audio.tsx
> +    if (ref) {
Поправил)

2023-07-08 19:29 UTC, romka008 commented on packages/client/src/components/Audio/Audio.tsx
> +      if (ref) {
Тоже

2023-07-08 19:29 UTC, romka008 commented on packages/client/src/components/Audio/Audio.tsx
> +    audioRef.current.volume -= 0.1;
Готово

2023-07-08 19:30 UTC, romka008 commented on packages/client/src/components/Audio/Audio.tsx
> +            {isPlay ? (
@IvanPeleshok Иван, тут нельзя так сделать, так как мы используем преттиер, и разработчики библиотеки в данном треде повторно написали, что это не то что они собираются делать [клик](https://translated.turbopages.org/proxy_u/en-ru.ru.5a4b768c-64a9b5ab-ce2cd614-74722d776562/https/github.com/prettier/prettier/issues/4714)

2023-07-08 19:36 UTC, romka008 commented
@IvanPeleshok Спасибо за ревью)

2023-07-08 20:09 UTC, IvanPeleshok approved these changes

2023-07-10 05:23 UTC, ahikyoshi approved these changes

2023-07-10 05:49 UTC, kluk42 approved these changes

2023-07-10 06:24 UTC, merged