Feat/jus 51
Just-Rock-Stars/black-hole pull request #33
Opened 2023-07-10 05:11 UTC by ahikyoshi

### Какую задачу решаем

Создание лидерборда

### Скриншоты/видяшка (если есть)

### TBD (если есть)

Сделать потом пагинацию и выбор между просмотром очков и поглащенным объектов на клиенте

2023-07-10 15:23 UTC, romka008 requested changes

2023-07-10 15:23 UTC, romka008 commented on packages/client/src/pages/Leaderboard/types.ts
> +    userID: number;
Не хватает 
`userAvatar: string | null`

2023-07-12 07:16 UTC, romka008 approved these changes

2023-07-12 07:40 UTC, kluk42 approved these changes

2023-07-12 07:40 UTC, kluk42 commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +    const userData = localStorage.getItem('user');
у нас есть типизированная функция в localStorage.ts. Лучше использовать её

2023-07-12 07:40 UTC, kluk42 commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +    leaderboardApi
В дальнейшем надо будет запилить лоадер для таких вещей

2023-07-12 07:43 UTC, ahikyoshi commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +    const userData = localStorage.getItem('user');
Не видел, такого. И в моей ветке его точно нет, мы искали на созвоне, кто-то ее убрал. Если я ошибаюсь подскажи в каком файле

2023-07-12 07:44 UTC, ahikyoshi commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +    leaderboardApi
Это мы будем делать на неделе доработок, там еще пару вещей есть которые ждет лидерборд

2023-07-12 07:52 UTC, kluk42 commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +    const userData = localStorage.getItem('user');
Сорян, протупил, это я её в своём пр добавлял, который ещё не смёржен :) Тоже надо таску завести под это дело на будущее

2023-07-12 12:46 UTC, IvanPeleshok commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +      .then((res) => setLeaders(res.data));
Предлагаю переписать на async / await + try / catch
https://learn.javascript.ru/async-await

2023-07-12 12:46 UTC, IvanPeleshok commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +            <li className="py-2 flex text-center text-sm odd:bg-white/20" key={userID}>
Декомпозировать сущность, создав для неё отдельный вью компонент

2023-07-12 12:49 UTC, IvanPeleshok commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +        <li
```
<li
          className={
            (0 < currentPage && currentPage < 11)
              ? 'p-2 mr-1 bg-white/50 rounded-sm'
              : 'p-2 mr-1 cursor-pointer rounded-sm hover:bg-white/30'
          }
          onClick={() => setCurrentPage(currentPage)}
        >
          {currentPage}
  </li>
```

2023-07-12 16:18 UTC, Qtrixnet commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +        <li
@ahikyoshi в проекте кстати clsx подключена для классов

2023-07-12 16:22 UTC, Qtrixnet commented on packages/client/src/api/leaderboardApi/types.ts
> +  data: {
для чистоты можно в отдельный интерфейс вынести, чтоб плоский тип был

2023-07-12 16:23 UTC, Qtrixnet commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +        userDisplayName: user.display_name,
мы где-то что-то упустили) snake case в js это плохо. Кажется нам нужен адаптер, чтобы на фронте был везде camelCase, наверное можно это в отдельную таску добавить

2023-07-14 06:22 UTC, aleksandr-kiliushin commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +        userDisplayName: user.display_name,
Создал задачу

2023-07-14 06:29 UTC, aleksandr-kiliushin approved these changes

2023-07-14 07:41 UTC, Qtrixnet commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +        userDisplayName: user.display_name,
Есть образец, можно будет потестить, в таске добавлю

2023-07-17 02:25 UTC, ahikyoshi commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +            <li className="py-2 flex text-center text-sm odd:bg-white/20" key={userID}>
Вынес в отдельный компонент

2023-07-17 02:26 UTC, ahikyoshi commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +        userDisplayName: user.display_name,
@Qtrixnet, а где тут snake case?

2023-07-17 04:42 UTC, Qtrixnet commented on packages/client/src/pages/GameEnd/GameEnd.tsx
> +        userDisplayName: user.display_name,
@ahikyoshi `user.display_name`

2023-07-17 04:55 UTC, kluk42 commented on packages/client/src/pages/Leaderboard/utils.ts
> +export const paginationPages = function (leaders: TLeaderboardItems[]) {
Можно попробовать сделать более универсальную утилиту для пагинации, которая будет работать для любых компонентов. Также можно переработать `paginationLeaders` через дженерик. Но у нас пагинация только для лидерборда, так что некритично

```
(items: unknown[], itemsPerPage: number) => {
  return items.filter((_, index) => index % itemsPerPage === 0).map((_, index) => index);
};
```

2023-07-17 04:56 UTC, kluk42 approved these changes

2023-07-17 19:34 UTC, IvanPeleshok commented on packages/client/src/components/Pagination/Pagination.tsx
> +                page === currentPage
Рекомендация: если по условиям добавляем класс, то лучше как-то так:
```
// Objects (variadic)
```
https://www.npmjs.com/package/clsx#:~:text=clsx(%7B%20foo%3Atrue%20%7D%2C%20%7B%20bar%3Afalse%20%7D%2C%20null%2C%20%7B%20%27%2D%2Dfoobar%27%3A%27hello%27%20%7D)%3B

2023-07-17 19:34 UTC, IvanPeleshok approved these changes

2023-07-18 04:22 UTC, merged