Feat/jus 49
Just-Rock-Stars/black-hole pull request #34
Opened 2023-07-10 05:37 UTC by kluk42

### Какую задачу решаем
Роутинг для ssr
Предзагрузка данных на сервере для redux

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-10 16:06 UTC, aleksandr-kiliushin requested changes

2023-07-10 16:06 UTC, aleksandr-kiliushin commented on packages/server/tsconfig.json
> +    "../server"
Это то же самое, что и "./"? Если правильно понимаю как оно работает, то нод модули также попадут под анализ TS и он может начать лагать. 
Как предлагаю:
1. Можешь добавить в include точечно интересующие файлы (то есть продолжать как строками выше)
2. или оставить как есть, но убрать все файлы выше ("./" включает их всех), и сделать exclude: ["./node_modules"]

2023-07-11 10:24 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Profile/Profile.tsx
> +      id: Number(id),
Number лишний теперь

2023-07-11 10:24 UTC, aleksandr-kiliushin approved these changes

2023-07-12 13:07 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/Profile.tsx
> +    const {
Предлагаю эту логику вынести в redux-thunk
И всё взаимодействие запросов и строка производить там
https://redux.js.org/usage/writing-logic-thunks
https://www.youtube.com/watch?v=93CR_yURoII

Если в рамках этого PR нет желания переезжать, то советую записать на это отдельную задачку

2023-07-12 13:10 UTC, IvanPeleshok requested changes
Есть вопросы по взаимодействию сервера и хранилища

2023-07-16 05:53 UTC, kluk42 commented on packages/client/src/pages/Profile/Profile.tsx
> +    const {
Создал таску под это на доске

2023-07-16 09:59 UTC, IvanPeleshok approved these changes

2023-07-17 04:16 UTC, merged