wip topics
Just-Rock-Stars/black-hole pull request #40
Opened 2023-07-21 14:55 UTC by kluk42

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-22 14:45 UTC, aleksandr-kiliushin requested changes

2023-07-22 14:45 UTC, aleksandr-kiliushin commented on packages/server/db.ts
> +  host: 'localhost',
В `host` должно быть имя сервиса с БД из файла `compose.dev.yml`, т.е. `"postgres"`

2023-07-22 14:45 UTC, aleksandr-kiliushin commented on packages/server/db.ts
> +      host: 'localhost',
В `host` должно быть имя сервиса с БД из файла `compose.dev.yml`, т.е. `"postgres"`

2023-07-22 14:45 UTC, aleksandr-kiliushin commented on packages/server/db.ts
>  import { Client } from 'pg';
`import { Client }`, объявление и вызов `createClientAndConnect` больше не нужны  
`sequelize` – это замена для `"pg"`, эти два пакета делают одно и то же  
Пакет `pg" можно попробовать удалить из зависимостей, но не уверен – возможно `sequelize` использует под капотом `pg` и полагается, что он установлен

2023-07-22 14:45 UTC, aleksandr-kiliushin commented on packages/server/db.ts
> +  models: [__dirname + '\\src\\Models'],
Так работать будет только на винде  
Чтобы работало на всех ОС (в докере в том числе), надо заюзать `path.join`  

```suggestion
  import path from 'node:path';
  // ...
  models: [path.join(__dirname, 'src', 'Models')],
```

2023-07-23 06:47 UTC, kluk42 commented on packages/server/db.ts
>  import { Client } from 'pg';
Удалить не получится https://sequelize.org/docs/v6/getting-started/

2023-07-23 10:52 UTC, aleksandr-kiliushin approved these changes

2023-07-23 10:52 UTC, aleksandr-kiliushin commented on packages/server/tsconfig.json
> +      "*": ["types/*"],
Как это работает?

2023-07-23 10:52 UTC, aleksandr-kiliushin commented on .eslintrc.js
> +    'no-restricted-syntax': [0],
Зачем ж  
Дефолтные экспорты вносят щепотку хаоса в ориентацию по кодовой базе и в нейминг

2023-07-23 10:54 UTC, aleksandr-kiliushin commented on packages/server/tsconfig.json
> +      "*": ["types/*"],
а, это еще до тебя было написано (`"*": ["types/*"]`). Тем не менее все равно интересно, что делает эта строка

2023-07-24 06:26 UTC, IvanPeleshok commented on packages/server/src/Models/ForumTopic.ts
> +}
Рекомендация: оставлять в каждом файле пустую строку в конце файла и вот почему: https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2023-07-24 06:27 UTC, IvanPeleshok commented on packages/server/src/routes/router.ts
> +router.use('/api/' + Routes.Forum, forumRouter);
Рекомендация: api + версионирвание можно вынести в отдельный модуль (на подумать)

2023-07-24 06:29 UTC, IvanPeleshok commented on packages/server/src/services/topicsService.ts
> +      if (authorId) {
Рекомендация: для того, чтобы код был максимально читаемым (простым), предлагаю отказываться от ветвления и конструкцию if / else писать следующим образом:
```
if () {
 ...
 return
}

// else 
```

2023-07-24 06:31 UTC, IvanPeleshok approved these changes
Оставил рекомендации
Хорошая работа :)

2023-07-24 08:53 UTC, kluk42 commented on packages/server/src/routes/router.ts
> +router.use('/api/' + Routes.Forum, forumRouter);
Типа сделать отдельный проект под апишку?

2023-07-24 08:54 UTC, merged