Feat/jus 65
Just-Rock-Stars/black-hole pull request #45
Opened 2023-07-25 08:30 UTC by ahikyoshi

### Какую задачу решаем

Подключаем Api Форума

### Примечание

По времени было невозможно разработать ветку отдельно и влить в дев. Поэтому все изменения совершенные мной были сделаны в папке client. Спасибо что прочли

2023-07-26 11:49 UTC, aleksandr-kiliushin requested changes

2023-07-26 11:49 UTC, aleksandr-kiliushin commented on packages/client/src/constants/index.ts
> +
назвать можно `CUSTOM_API_BASE_URL` или как-то так. Но не FORUM, так как на этот урл будут обращаться и темы и эмоджи и все остальное

2023-07-26 11:49 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Topic.tsx
> +    axios.get('http://localhost:3001/api/comments?topicId=34').then((res) => setCommets(res.data));
Не забудь вместо захардкоженного айди 34 взять его динамически из урла или из состояния  

А также заменить `axios.get` на `forumApi.getComments` раз уж начал собирать эндпоинты в `forumApi`

2023-07-26 11:49 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Topic.tsx
> +          {/* {comments.map(({ content, author, time, id }, index) => {
раскомментить не забудь

2023-07-26 11:49 UTC, aleksandr-kiliushin commented on packages/client/src/pages/Forum/Topic.tsx
> +          {/* <textarea
раскомментить не забудь

2023-07-26 19:03 UTC, aleksandr-kiliushin approved these changes

2023-07-27 01:15 UTC, bin-umar requested changes
Привет! Я ревьюер из Я.Практикума.

Местами немного захардкожено вызов апи, поправь, пожалуйста, и добавь скриншоты в описание PR.

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/types.ts
> +  idTopicList: string | undefined;
```suggestion
  idTopicList?: string;
```

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/api/forumApi/forumApi.ts
> +  forumId: string | undefined;
Это то же самое что
```suggestion
  forumId?: string;
```

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/api/forumApi/forumApi.ts
> +const getAllTopics = (id: string) => {
некоторые IDE показывают название аргумента, поэтому для простоты понимания будет круче наименовать 
```suggestion
const getAllTopics = (forumId: string) => {
```

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/constants/index.ts
> +
Согласен!

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/Comment.tsx
> +    axios.get(`ya-praktikum.tech/api/v2/user/${yaId}`).then((res) => setUserData(res.data));
А разве не через api/v2 должны обращаться к этому апи?

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/Comment.tsx
> +            src={userData.avatar != null ? userData.avatar : randomAvatarPath}
```suggestion
            src={userData.avatar ?? randomAvatarPath}
```

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/Topic.tsx
> +      .get(`http://localhost:3001/api/comments?topicId=${params.idTopic}`)
Необходимо по аналогии Forum, сделать такой ж для комментов

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/Topic.tsx
> +  useEffect(() => {}, [comments]);
?

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/Topic.tsx
> +    const userData = localStorage.getItem('user');
У вас нету Redux-а?

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/TopicList.tsx
> +    }
Старайся написать код как можно плавнее (то есть уменьшать уровень вложенности).
```suggestion
    if (!idTopicList) {
       return;
    }
    
    forumApi
        .getAllTopics(idTopicList)
        .then((topicsList) => setTopics(topicsList.data))
        .catch((e) => console.log(e));
```
https://learn.javascript.ru/coding-style#urovni-vlozhennosti

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/TopicList.tsx
> +              {idTopicList === '1' ? 'Обсуждение игровых моментов' : 'Технические вопросы'}
А если будет больше разделов?

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/TopicList.tsx
> +          return <TopicItem data={topicData} idTopicList={idTopicList} key={idTopicList} />;
Один key не может использоваться в нескольких компонентах.

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/components/NewTopic/NewTopic.tsx
> +      authorName: user.display_name === null ? user.first_name : user.display_name,
```suggestion
      authorName: user.display_name ?? user.first_name,
```

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/components/NewTopic/NewTopic.tsx
> +  const publicNewTopic = function () {
Ключевое слово function тут излишнее

2023-07-27 01:15 UTC, bin-umar commented on packages/client/src/pages/Forum/components/TopicItem/TopicItem.tsx
> +          src={userData.avatar != null ? userData.avatar : randomAvatarPath}
```suggestion
          src={userData.avatar ?? randomAvatarPath}
```

2023-07-27 02:37 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Topic.tsx
> +    const userData = localStorage.getItem('user');
Есть, но по печальной судьбе юзер у нас не храниться

2023-07-27 02:38 UTC, ahikyoshi commented on packages/client/src/pages/Forum/types.ts
> +  idTopicList: string | undefined;
Изменил, что-то забыл что так можно

2023-07-27 02:38 UTC, ahikyoshi commented on packages/client/src/api/forumApi/forumApi.ts
> +const getAllTopics = (id: string) => {
Спасибо за совет!

2023-07-27 02:39 UTC, ahikyoshi commented on packages/client/src/constants/index.ts
> +
Тоже согласен сделал

2023-07-27 02:40 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Comment.tsx
> +    axios.get(`ya-praktikum.tech/api/v2/user/${yaId}`).then((res) => setUserData(res.data));
Да, я думал вы позже посмотрите, поэтому сделал эту тестовую версию, но она не работает. Сейчас переделал на кастомный api

2023-07-27 02:40 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Comment.tsx
> +            src={userData.avatar != null ? userData.avatar : randomAvatarPath}
Даже не знал что так можно

2023-07-27 02:40 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Topic.tsx
> +      .get(`http://localhost:3001/api/comments?topicId=${params.idTopic}`)
Сделал

2023-07-27 02:41 UTC, ahikyoshi commented on packages/client/src/pages/Forum/Topic.tsx
> +  useEffect(() => {}, [comments]);
Сначала не понял в чем правка, потом допёр. Это сделано было в спешке, потому что уже не успевал нормально сделать. У нас что-то с докером, и я после каждой правке на фронте жду 2 минуты для изменений

2023-07-27 02:46 UTC, ahikyoshi commented on packages/client/src/pages/Forum/TopicList.tsx
> +    }
Узнал это на обучении, но пока забываю это использовать

2023-07-27 02:52 UTC, ahikyoshi commented on packages/client/src/pages/Forum/TopicList.tsx
> +              {idTopicList === '1' ? 'Обсуждение игровых моментов' : 'Технические вопросы'}
Это константа по факту, менять её не собираемся. А если решим все таки расширить, сделаю запрос на сервер из листа топиков по апи списка форума. Пока считаю излишним

2023-07-27 07:18 UTC, bin-umar commented on packages/client/src/pages/Forum/Comment.tsx
> +            src={userData.avatar != null ? userData.avatar : randomAvatarPath}
Прочитай про него, удобная штука https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

2023-07-27 07:19 UTC, bin-umar commented on packages/client/src/pages/Forum/Topic.tsx
> +    const userData = localStorage.getItem('user');
Сложно его туда добавить? В целом вопрос не к конкретному ПР-у.

2023-07-27 07:26 UTC, bin-umar approved these changes
Аппрув!
Касательно оператора нулевого слияния (??)
https://learn.javascript.ru/nullish-coalescing-operator

2023-07-27 07:26 UTC, bin-umar commented on packages/client/src/api/forumApi/forumApi.ts
> +const getTopicComments = (id: string) => {
Ну и тут же аналогично можно сделать :)
```suggestion
const getTopicComments = (topicId: string) => {
```

P.S. не критично. Up to u

2023-07-27 07:26 UTC, bin-umar commented on packages/client/src/pages/Forum/Topic.tsx
> +    if (params.idTopic != undefined) {
Рекомендуется всегда использовать [строгое сравнение](https://learn.javascript.ru/comparison#strogoe-sravnenie).

2023-07-27 14:13 UTC, merged