Jus 62
Just-Rock-Stars/black-hole pull request #46
Opened 2023-07-25 15:35 UTC by romka008

### Эмоджи/Реакции (бэкенд)
Строго не судите, это один из первых опытов написания бэкенда, отнеситесь с пониманием)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-25 15:57 UTC, aleksandr-kiliushin approved these changes

2023-07-25 15:57 UTC, aleksandr-kiliushin commented on packages/server/src/services/reactionService.ts
> +        await Reaction.update(
Что значит "обновить реакцию"?  
Реакцию можно: 1. поставить, и 2. снять.  
Или что-то упускаю

На первый взгляд, много логики, которая, возможно, не нужна.  
Вижу этот сервис как 2 простых метода:  
1. `createTopicReaction() { Reaction.create({ ... }) }`
2. `createTopicReaction() { Reaction.destroy({ ... }) }`

2023-07-25 16:51 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +        await Reaction.update(
@aleksandr-kiliushin тут предусмотрел возможность изменения реакции к топику, если поле «type» придет с другим значением, а остальные поля без изменений, то реакция/эмоджи изменится

2023-07-25 19:30 UTC, Olegas requested changes
Добрый вечер.
Есть замечания по коду, нужно переделать.
Написал подробные комментарии как и почему.

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/controllers/reaction.ts
> +      const result = await this.reactionService.createReaction(req.body);
Тут проблема. Идентификатор пользователя, которому принадлежит реакция, берется напрямую из тех данных, которые пользователь сам отправил в запросе.
Если у вас уже реализована проверка авторизации на запросы к API данные о пользователе надо брать оттуда. Иначе пользователь сможет постить реакции от имени других людей.

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +    const topic = await ForumTopic.findByPk(topicId);
Если уж делать проверки, то 
1. Я бы добавил проверку того, что все аргументы в принципе переданы (как сделано для type)
2. Проверку на наличие аргументов (и type в том числе) перенес в самый верх - что бы сперва проверить наличие аргументов а потом уж идти в базу

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +        });
Тут ошибка. Нужно передавать объект транзакции в вызовы ORM, иначе они никак с ней связаны не будут. Т.е. да, транзакций завершится когда все вызовы отработают или откатится если любой из них упадет, но сами вызовы НЕ будут принадлежать ей.
https://sequelize.org/docs/v6/other-topics/transactions/

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +      if (reactionDestroy) {
Судя по этому условию, в проекте предполагается, что у данного пользователя может быть всего одна реакция на данный пост. Значит должен быть уникальный индекс, который не допустит вставку дублей
Завернуть операцию в транзакцию - не поможет

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +      );
Тут что-то странное.
С одной стороны проверяется, если реакция именно такая есть то ее удалим, если такой нет но есть другая, мы ее обновим. А потом сразу же создадим еще одну. Явно какая-то ошибка.
Я бы сделал иначе:
1. Отдельное API на создание реакции, отдельное на удаление, иначе каша. Называется create а делает все что можно
2. В модели сделал уникальный индекс UserId, TopicId
3. При создании использовал подход upsert (то есть попытаться создать, в случае дубля - обновить). Дубли могут получиться при конкурирующих запросах.

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +        };
Очень странно, что API возвращает или текст или объект. Скорее всего с таким API будет не особо удобно работать, такой вызов сложно типизировать.

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +    const topic = await ForumTopic.findByPk(topicId);
Тут бы тоже проверить на то что topicId задан

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +            updatedAt: creationDate,
А разве ORM сам не заполняет эти поля?

2023-07-25 19:30 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +        await Reaction.update(
Полностью согласен с Александром

2023-07-27 13:16 UTC, romka008 commented on packages/server/src/controllers/reaction.ts
> +      const result = await this.reactionService.createReaction(req.body);
Добавил проверка авторизации и теперь можно доставить данные пользователя оттуда

2023-07-27 13:16 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +    const topic = await ForumTopic.findByPk(topicId);
Поправил

2023-07-27 13:28 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +        });
Да, точно, тут я ошибся

2023-07-27 13:35 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +      if (reactionDestroy) {
Я теперь беру уникальный Id пользователя из запроса по `https://ya-praktikum.tech/api/v2/auth/user`.
У одного топика может быть только 1 реакция по этому id, если приходит такой же topiId и user.Id (id пользователя), то реакция к этому топику обновится.

2023-07-27 13:37 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +      );
Не получилось использовать этот подход upsert, сделал немного иначе, выше уже писал)

2023-07-27 13:37 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +        };
Убрал этот текст, теперь возвращаю объект, а тест только на удаление

2023-07-27 13:38 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +    const topic = await ForumTopic.findByPk(topicId);
Поправил

2023-07-27 13:38 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +            updatedAt: creationDate,
+

2023-07-27 16:28 UTC, Olegas requested changes
Стало лучше, но не до конца. Отсутствие уникальных индексов по прежнему проблема.
Использование в коде паттерна "проверили, если нет - создали" при отсутствии уникальных индексов - это проблема.
Если не получается upsert - напиши что именно не получается, я помогу.

2023-07-27 16:28 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +        YaId: user.id,
Вы создаете пользователя без обработки ситуации, что он может быть уже есть в базе. То что вы строкой выше проверили - ничего не гарантирует. Между этими двумя асинхронными операциями могла вклиниться обработка какого-то другого запроса где тоже создастся пользователь. 
У вас должен быть уникальный индекс на YaId и видимо надо использовать операцию типа getOrCreate

2023-07-27 16:28 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +        },
Я так и не увидел создание уникального индекса на эту пару полей. Скорее всего именно по этой причине upsert и не сработал. Он не может работать без уникального индекса.

2023-07-27 16:28 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +      if (reaction) {
И вот тут снова проблема. Между проверкой и созданием - нет гарантии что кто-то другой не создаст запись. Тут поможет только уникальный индекс и upsert.

2023-07-27 16:28 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +    };
Странно. Формат ответа от одной и той же ручки в разных случаях отличается.

2023-07-29 06:32 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +        YaId: user.id,
Очень хороший метод, все одной операцией, спасибо)

2023-07-29 06:36 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +        },
Исправил, из-за того что я не знал как именно в базе должны отображаться уникальные индексы, я не понимал добавились ли они. 
Как оказалась модели не обновлялись в базе. 
Я позже просто все снес, и все поставил и запустил, и заработало)))

2023-07-29 06:37 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +      if (reaction) {
Сделал

2023-07-29 06:37 UTC, romka008 commented on packages/server/src/services/reactionService.ts
> +    };
Не совсем понял здесь, у меня не отличается формата ответа. 
Можешь примеры показать?

2023-07-29 06:52 UTC, Olegas requested changes
Уже почти все хорошо, но не до конца. Смотри, в таблице с реакциями ты сделал уникальный индекс на поле UserId и уникальный индекс на поле TopicId. Что получилось теперь:
1. Пользователь с идентификатором 1 добавляет реакцию на топик 2 - пока все хорошо
2. Пользователь 1 добавляет реакцию на топик 3 - все сломалось. Потому что значение в UserId больше не уникальное.
То же самое произойдет, если два разных юзера добавят реакцию на один топик - будет нарушена уникальность идентификатора топика.
Тебе нужен один индекс на два поля сразу. Должна быть уникальная пара значений, а не каждое в отдельности

2023-07-29 06:52 UTC, Olegas commented on packages/server/src/Models/User.ts
> +    @Unique
Тут все хорошо

2023-07-29 06:52 UTC, Olegas commented on packages/server/src/Models/Reaction.ts
> +    @Unique
А тут - нет.

2023-07-29 06:52 UTC, Olegas commented on packages/server/src/services/reactionService.ts
> +    };
Тут сейчас все хорошо

2023-07-29 15:28 UTC, romka008 commented on packages/server/src/Models/Reaction.ts
> +    @Unique
@Olegas наверное должно быть так `@Unique("UserId-TopicId")`
Спасибо тебе за такое качественное ревью!)

2023-07-29 19:23 UTC, Olegas approved these changes
Теперь все супер! Получился отличный бэкэнд для эмодзи! Ура!

2023-07-31 14:37 UTC, merged