Feat/jus 14
Just-Rock-Stars/black-hole pull request #8
Opened 2023-05-30 08:03 UTC by kluk42

### Какую задачу решаем
JUS-14: сделана страница логина с логикой авторизации.
JUS-17: сделана валидация форм регистрации и авторизации
JUS-18: добавлена страница регистрации (см. второй скриншот)

### Скриншоты/видяшка (если есть)
![image](https://github.com/aleksandr-kiliushin/black-hole/assets/63767882/46d4a524-01b7-47ea-ba35-ef1469998118)
![image](https://github.com/aleksandr-kiliushin/black-hole/assets/63767882/3e3ab9e2-ccda-48ed-90eb-e65b26dc083c)
![image](https://github.com/aleksandr-kiliushin/black-hole/assets/63767882/d532a8d9-d3c7-4f3f-a65f-520dad0c7cbb)

### TBD (если есть)

##Логика авторизации
Все действия вокруг авторизации осуществляются с помощью класса AuthApi, который использует для этого единый инстанс аксиоса нашего приложения. После успешной регистрации пользователь перенаправляется на страницу авторизации. После успешной авторизации пользователь перенаправляется на страницу своего профиля

2023-05-30 08:39 UTC, Qtrixnet commented on .prettierrc
> +  "semi": true,
Ты по привычке включил?) было же так чисто без них

2023-05-30 08:39 UTC, Qtrixnet commented on packages/client/src/App.tsx
> +  { path: '/login', Component: LoginPage },
Как предложение, сделать:
- login / register
либо
- sign-un / sign-up

2023-05-30 08:39 UTC, Qtrixnet commented on packages/client/src/pages/Signup/SignUp.tsx
> +        <AppLink to={'/login'} title="Войти">
to="/login" :)

2023-05-30 08:42 UTC, Qtrixnet commented on package-lock.json
у нас же вроде не должно быть package-lock? так как yarn в проекте? 
14к изменений чет много для ПР))

2023-05-30 08:47 UTC, kluk42 commented on .prettierrc
> +  "semi": true,
Ага, что-то глаз мне мозолило их отсутствие) Если никто против не будет, то я бы оставил

2023-05-30 08:51 UTC, kluk42 commented on packages/client/src/pages/Profile.tsx
> +        onClick={() => authApi.SignOut()}
Ага, так лучше

2023-05-30 08:58 UTC, kluk42 commented on packages/client/src/App.tsx
> +  { path: '/login', Component: LoginPage },
го с дефисами

2023-05-30 09:27 UTC, Qtrixnet commented on package-lock.json
@aleksandr-kiliushin есть идеи почему так? выглядит как 2 менеджера пакетов в одном проекте

2023-05-30 10:35 UTC, Qtrixnet commented
кажется беда с мобилкой) 

![image](https://github.com/Just-Rock-Stars/black-hole/assets/67040346/443a24d5-ba38-45a0-a2fd-4df51803c5e9)

2023-05-30 12:58 UTC, aleksandr-kiliushin commented on package-lock.json
В `dev` нет package-lock.json, и тут он не нужен. Наверное, `npm install` случайно запустил

2023-05-31 10:44 UTC, kluk42 commented on .prettierrc
> +  "semi": true,
Раз никто не против, то резолвю

2023-05-31 12:07 UTC, aleksandr-kiliushin commented on packages/client/src/components/Button/Button.tsx
> +        `bg-blue-700 hover:bg-blue-800
Для этих целей в тайлвинд есть директива `@layer components`

https://tailwindcss.com/docs/functions-and-directives#layer


```
@layer components {
  .btn-blue {
    @apply bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded;
  }
}
```

Этот многострочный набор классов лучше вынести в CSS файл и заюзать тут

Вариант с классом лучше тем, что этим классом потом можно будет стилизовать и ссылки

2023-05-31 12:09 UTC, aleksandr-kiliushin commented on packages/client/src/components/Button/Button.tsx
> +        `bg-blue-700 hover:bg-blue-800
Вообще, компонент кнопки не нужен до тех пор, пока он не имеет каких то специфичных пропов.  
Достаточно заюзать уже имеющийся CSS-класс "btn-primary"  

`<button className="btn-primary">Выйти из профиля</button>`

2023-05-31 12:10 UTC, aleksandr-kiliushin commented on packages/client/src/components/FormButton/FormButton.tsx
> +    <div className={clsx(containerClassName, '')}>
Зачем объединение с пустой строкой?

2023-05-31 12:12 UTC, aleksandr-kiliushin commented on packages/client/src/components/Input/Input.tsx
> +            { [inputError]: !!validationError }
Без этого вынесения будет лучше:
`{ "border-red-500": !!validationError }` даже более понятно

Если хочешь с вынесением, то дай переменной более точное имя, например  `invalidInputClassName`

2023-06-01 03:55 UTC, Qtrixnet requested changes

2023-06-01 04:48 UTC, kluk42 commented on packages/client/src/components/AppLink/AppLink.tsx
> +export const AppLink = ({ className, ...props }: AppLinkProps) => {
Тут утиная нотация вполне норм срабатывает

2023-06-01 04:49 UTC, kluk42 commented on packages/client/src/components/Button/Button.tsx
> +        `bg-blue-700 hover:bg-blue-800
Единый компонент кнопки удобно использовать по всей апки, если у нас будет что-то наподобие стайл гайда

2023-06-01 04:52 UTC, kluk42 commented on packages/client/src/components/AppLink/index.ts
> +export { AppLink as default } from './AppLink';
А зачем тогда делать такие импорты? Можно же тогда просто импортить из файла компонента

2023-06-01 05:06 UTC, kluk42 commented on .yarnrc.yml
> +nodeLinker: node-modules
Автоматически сгенеренный файл. Видимо, yarn это зачем-то понадобилось. https://yarnpkg.com/configuration/yarnrc#nodeLinker

2023-06-01 06:50 UTC, aleksandr-kiliushin approved these changes

2023-06-01 10:43 UTC, Qtrixnet approved these changes

2023-06-01 10:43 UTC, Qtrixnet commented on packages/client/src/components/AppLink/index.ts
> +export { AppLink as default } from './AppLink';
Победили, победили) это не настолько критичная штука в этом проекте, чтобы холиварить по этому поводу. Я топлю не именно за использование реэкспортов, а за их консистентность. Один раз предложил и мы начали их использовать, теперь проверяю чтобы везде было одинаково. Давайте тогда в конвенцию внесем правило и сделаем везде одинаковые импорты/экспорты

2023-06-02 08:36 UTC, bin-umar requested changes
Привет! Я ревьюер из Я.Практикума.
В целом довольно-таки приятный и читабельный код, молодцом! Местами дублирование и чуть избыточность, поправь пжл эти мелкие моменты, и го аппрувить.

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/GameEnd/GameEnd.tsx
Не рекомендую добавить такие лишние изменения в PR-е где сдаёте индивидуальный зачёт, это мозолит глаза и мешает ревью.

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/api/Auth/Auth.ts
> +export class AuthApi implements IAuth {
Мне кажется стоит такие классы экспортировать синглтоном, потому что так проще и удобнее с ними взаимодействовать, если нет причины не сделать их такими.

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      await submit(data);
Почему бы тут просто не сделать вызов authApi напрямую:
```suggestion
      await authApi.SignIn(data);
```
В чём смысл добавить ещё один слой?

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      await submit(data);
Второй момент что у вас нигде не указано что SignIn это асинхронная функция, а тут делаете await

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      const errorMessage = typedError?.message;
anyTypedError? :))

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/SignIn/SignIn.tsx
> +        setError('root', { message: errorMessage, type: 'server' });
Если вы потом этот message показываете где-то в UI то не очень хорошо так делать, так как это ошибки сети или что-то подобное, юзеру лучше показывать человекочитаемые ошибки.

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/SignIn/validationUtils.ts
> +  if (password === null || password === '') {
Не проще ли?
```suggestion
  if (!password) {
```

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/SignIn/validationUtils.ts
> +    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,40}$/;
Так как выше уже проверяете длинноту, может быть будет проще убрать из `{8,40}`

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/SignIn/validationUtils.ts
> +  const regEx = new RegExp('^[A-Za-z0-9]*$');
где-то через new RegExp, где-то просто. Для консистентности лучше сделай одинаковым
```suggestion
  const regExp = /^[A-Za-z0-9]*$/;
```

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/Signup/validationUtils.ts
> +};
У вас идёт повторение этих двух функций, не должно быть такого, прощу объединить их в одном месте. Лучше просто сделать папку для валидации и поместить всё в одном месте.

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/Signup/validationUtils.ts
> +    return 'Логин может состоять только из букв латинского алфавита или кирилицы';
Это 'Логин' или 'Имя'?

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/Signup/validationUtils.ts
> +  }
https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/Signup/validationUtils.ts
> +  }
По моему функция trim тут излишняя, так как можно проще:
```suggestion
  if (!value) {
    return 'Поле обязательно для ввода';
  }
  
  const name = value.trim();
```

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/Signup/validationUtils.ts
> +};
На будущее: Есть отличнейшая утилита для парсинга и валидации номера телефонов, https://www.npmjs.com/package/libphonenumber-js, можете воспользоваться в реальной работе.

2023-06-02 08:36 UTC, bin-umar commented on packages/client/tailwind.config.js
> +        '464px': '464px',
В чём смысл?

2023-06-02 08:36 UTC, bin-umar commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      await submit(data);
Имею в виду, что не хватает именно ключевое слово "async"

2023-06-02 09:27 UTC, kluk42 commented on packages/client/src/components/Input/Input.tsx
> +        {label !== undefined && (
!'0' === false Несколько раз обжигался об это, завёл привычку на такие тупые проверки

2023-06-02 09:27 UTC, kluk42 commented on packages/client/src/pages/Signup/validationUtils.ts
> +  }
омг

2023-06-02 09:28 UTC, kluk42 commented on packages/client/src/pages/Signup/validationUtils.ts
> +  }
опять-таки неочевидные проблемы с приведениями типов

2023-06-02 09:28 UTC, kluk42 commented on packages/client/src/pages/Signup/validationUtils.ts
> +};
найс, спасибо

2023-06-02 09:29 UTC, kluk42 commented on packages/client/tailwind.config.js
> +        '464px': '464px',
Не смог найти лучше способа, как в тэйлвинде задать константную ширину в пикселях. Завёл кастомный ключ. Выглядит уродливо, конечно

2023-06-02 10:55 UTC, kluk42 commented on packages/client/src/pages/Signup/validationUtils.ts
> +  }
Хотя согласен в случае имени trim это всё же оверкил

2023-06-02 17:16 UTC, bin-umar commented on packages/client/src/components/Input/Input.tsx
> +        {label !== undefined && (
Ну так твоя задача как раз таки не допускать невалидные значение, в твоём примере '0' валидное значение, и он пройдёт проверку.

Я кстати допустил ошибку, там нужен !!:
![Screenshot 2023-06-02 at 20 15 54](https://github.com/Just-Rock-Stars/black-hole/assets/15624993/ca1d2234-a5e2-4997-97da-4ac921aaa64d)
```suggestion
        {!!label && (
```

2023-06-02 17:17 UTC, bin-umar commented on packages/client/src/pages/Signup/validationUtils.ts
> +  }
Ты про 254? :)

2023-06-02 17:26 UTC, bin-umar commented on packages/client/src/pages/Signup/validationUtils.ts
> +};
@kluk42 тут излишнее дублирование кода, лучше утилиты связанные с валидацией объединить в одно место.

2023-06-03 07:43 UTC, kluk42 commented on packages/client/src/api/Auth/Auth.ts
> +export class AuthApi implements IAuth {
Оставлю оба варианта. Вдруг когда-нибудь класс для DI пригодится

2023-06-03 07:48 UTC, kluk42 commented on packages/client/src/components/Input/Input.tsx
> +        {label !== undefined && (
да чот натупил

2023-06-03 07:50 UTC, kluk42 commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      await submit(data);
дак я внутри SignIn не использую await, поэтому не объявлял её как асинхронную. Она просто промис возвращает

2023-06-03 15:47 UTC, bin-umar commented on packages/client/src/helpers/networkErrorToText.ts
может стоит удалить?

2023-06-03 15:52 UTC, bin-umar commented on packages/client/src/pages/Signup/SignUp.tsx
> +        }
FYI,  не очень правильно проверят строки (так как они довольно хрупкие и легко можно выстрелить себе в ногу), тем более из ответа апи. Для таких целей должен быть отдельное поле под название code (или reason_code).

2023-06-03 15:52 UTC, bin-umar commented on packages/client/src/pages/Signup/SignUp.tsx
> +      setHasRegistered;
это ж функция, почему она не вызывается?

2023-06-03 15:53 UTC, bin-umar commented on packages/client/src/pages/Signup/SignUp.tsx
> +      setHasRegistered;
```suggestion
      setHasRegistered(true);
```

2023-06-03 15:56 UTC, bin-umar commented
@kluk42 я правильно понимаю что ты все исправления которые хотел исправить, исправил?

2023-06-04 06:03 UTC, kluk42 commented on packages/client/src/pages/Signup/validationUtils.ts
> +  }
ага, бывают же адреса

2023-06-04 06:20 UTC, kluk42 commented on packages/client/src/pages/Signup/SignUp.tsx
> +        }
Эти поля по-хорошему должен устанавливать бэкэнд и в доке к апи указывать, какие значения какой проблеме соответствуют?

2023-06-04 06:21 UTC, kluk42 commented on packages/client/src/pages/Signup/SignUp.tsx
> +      setHasRegistered;
ага, пропустил

2023-06-04 06:31 UTC, kluk42 commented
> @kluk42 я правильно понимаю что ты все исправления которые хотел исправить, исправил?

да, сейчас вроде всё. Не привык к здешнему устройству пул-реквестов, поэтому пропускал иногда некоторые замечания. Сейчас вроде точно по всем прошёлся

2023-06-04 06:36 UTC, bin-umar commented on packages/client/src/pages/Signup/SignUp.tsx
> +        }
Да, правильно, сначала надо чтобы бэкенд их добавил. Если их нет, то можно оставить и так.

2023-06-04 06:37 UTC, bin-umar commented on packages/client/src/pages/Signup/SignUp.tsx
> +    return <Navigate to={'/sign-in'} />;
```suggestion
    return <Navigate to="/sign-in" />;
```
{} нужен чтобы передать какую либо переменную. Обычную строку проще передать напрямую.

2023-06-04 06:39 UTC, bin-umar commented on packages/client/src/pages/Signup/SignUp.tsx
> +    return <Navigate to={'/sign-in'} />;
Рекомендую добавить enum Route:
```ts
enum Route {
   SignIn = 'sign-in'
   Profile = 'profile'
}
```

2023-06-04 06:40 UTC, bin-umar approved these changes
Ставлю аппрув, но всё-таки рекомендую избавиться от велосипеда trim :)

2023-06-04 06:59 UTC, kluk42 commented
> Ставлю аппрув, но всё-таки рекомендую избавиться от велосипеда trim :)

@bin-umar спасибо за ревью!

2023-06-04 06:59 UTC, kluk42 commented on packages/client/src/pages/Signup/SignUp.tsx
> +        }
Ага, там ничего кроме строки нет

2023-06-04 07:05 UTC, merged